
public class printnamehundredtimes {
	
	public static void main(String agrs[])

	{
		/*print my name 100 times 
		 * manually print 10o times
		 */
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		System.out.println("Palak");
		
	}
}
